### ISSUE TITLE
Thanks a lot mate

### ISSUE THREAD

**Issue by lamhoangtung** [duydeja-vu/SHELL-SCRIPTS-DOCUMENTATION#1]
I think @DLH06 will find this useful :P

Again, thanks a lot @duydeja-vu ;)

**Comment by duydeja-vu** [comment]
Thank you for your interest .

**Comment by lamhoangtung** [comment]
@DLH06 pls say something ;(

**Comment by DLH06** [comment]
Really helpful in this time for me. :D Notice me when see simple satisfying things like this Lam :rainbow:
